### PR TITLE
Test LGTM.com automated code review (by adding code quality badges)

### PR DESCRIPTION
**Pull request by sjvs**
Now the C/C++ build is fixed, any PR should trigger analyses for both Python and C/C++ code. Let's see whether that's indeed the case!

### CODE REVIEW

**Comment by sjvs** [comment]
:smile:

**Comment by kthohr** [comment]
Great! Will the [main page](https://lgtm.com/projects/g/kthohr/gcem) update with the new C++ badge as well? 

Thanks again!

**Comment by sjvs** [comment]
Absolutely! The badge typically appears fairly soon after a new project (or language) is added, but it sometimes takes a while to appear for everybody because there's a fair bit of both server and client-side caching happening on LGTM.com. It has now appeared for me, but if it's not visible for you: please try refreshing your browser cache.

**Comment by kthohr** [comment]
Yep, all looks good now.

**Pull request merged**
